### ISSUE TITLE
Broken inheritance hierarchy when usign Pixate within Xamarin.Android app

### ISSUE THREAD

**Issue by mazurmichal** [Pixate/Xamarin-PixateFreestyle#7]
I'm trying to add Pixate to our cross-platform app built with Xamarin.

In Android app I'm using custom ListView and custom adapter which implements an interface. But when the Adapter property of the list view is being set to my custom adapter its base class is Java.Lang.Object instead of BaseAdapter and does not implement the interface anymore (cast will cause an exception).

Anyone had a similar issue with Pixate ? How do I fix it ?

**Comment by Shalom** [comment]
Pixate work on AdapterViews by proxying them in order to tag the recycled views with their new position (see https://github.com/Pixate/pixate-freestyle-android/blob/master/pixate-freestyle/src/com/pixate/freestyle/PXHierarchyListener.java#L232 ). This allows us to style more complex CSS expressions, like "nth-child" on a list.
Currently, that java.lang.reflect.Proxy is being created with a few known adapter interfaces, so the casting will fail if you would like to get your original BaseAdapter.

The good news is that we have a way to get to that original Adapter via PixateFreestyle.getAdapter(AdapterView<?> view). Then you can cast to your BaseAdapter. That should not cause any problem.

Cheers

**Comment by mazurmichal** [comment]
That works, thanks.
